# Generated by Django 4.0 on 2022-03-17 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_name', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'district',
            },
        ),
        migrations.CreateModel(
            name='Reasons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reasonName', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'reason',
            },
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_name', models.CharField(max_length=20)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.district')),
            ],
            options={
                'db_table': 'sector',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Full_name', models.CharField(max_length=80)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Male', max_length=6)),
                ('DoB', models.DateField()),
                ('phone_number', models.CharField(max_length=15)),
                ('levelofEducation', models.CharField(choices=[('P3', 'P3'), ('P4', 'P4'), ('P5', 'P5'), ('P6', 'P6'), ('S1', 'S1'), ('S2', 'S2'), ('S3', 'S3'), ('S4', 'S4'), ('S5', 'S5'), ('S6', 'S6')], max_length=4)),
                ('yearDropped', models.CharField(choices=[('2010', '2010'), ('2011', '2011'), ('2012', '2012'), ('2013', '2013'), ('2014', '2014'), ('2015', '2015'), ('2016', '2016'), ('2017', '2017'), ('2018', '2018'), ('2019', '2019'), ('2020', '2020'), ('2021', '2021')], max_length=6, null=True)),
                ('reason', models.CharField(choices=[('Academic Failure', 'Academic Failure'), ('Pregnancy', 'Pregnancy'), ('Financial Difficulties', 'Financial Difficulties'), ('Mental Illness', 'Mental Illness'), ('Drug Use/Addiction', 'Drug Use/Addiction'), ('Disabilities', 'Disabilities'), ('Retention', 'Retention'), ('Disengagement', 'Disengagement'), ('Transition', 'Transition')], max_length=200)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.district')),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.sector')),
            ],
            options={
                'db_table': 'student',
            },
        ),
    ]
