# Generated by Django 4.0 on 2022-03-17 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messageBody', models.TextField(max_length=300)),
                ('sector', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='base.sector')),
            ],
            options={
                'db_table': 'message',
            },
        ),
    ]
