# Generated by Django 4.0 on 2022-03-18 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_messages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.sector'),
        ),
    ]
